In [573]:
import numpy as np
import pandas as pd
import seaborn as sns

In [574]:
demo = pd.read_csv('/Users/mwilson/Documents/GitHub/surveys/data/temp/demo_data_orig.csv')
demo = demo.fillna(0)

In [575]:
demo['edu'] = demo['deg']/(demo['elem']+demo['ass']+demo['deg'])
demo['race'] = demo['white']/(demo['white']+demo['black']+demo['nat']+demo['aapi']+demo['mixed'])
demo['malefr'] = demo['male']/(demo['male']+demo['female'])
demo['femalefr'] = demo['female']/(demo['male']+demo['female'])

In [576]:
vote = pd.read_csv('/Users/mwilson/Documents/GitHub/election_forecast/data/temp/vote_data_clean.csv')

In [577]:
# fix the year format so we can work out which ones to average over

demo['years'] = demo['year'].str.split(pat='-')
def getyear1(row):
    return row['years'][0]
def getyear2(row):
    if(len(row['years'])>1):
        return row['years'][1]
    else:
        return row['years'][0]
demo['year1'] = demo.apply(getyear1, axis=1).astype(int)
demo['year2'] = demo.apply(getyear2, axis=1).astype(int)
demo['pres_year'] = 4*demo['year2'].floordiv(4)
cols_to_drop = ['year','years','year1','year2']
demo = demo.drop(cols_to_drop, axis=1)

# now drop a lot more, maybe too many

cols_to_drop = ['white','black','nat','aapi','mixed','elem','ass','deg','male','female']
demo = demo.drop(cols_to_drop, axis=1)

# remove Puerto Rico

demo = demo[demo['state']<57]

In [578]:
# average the data covering a given presidential year - can probably do better
# no data for 2004 so remove everything

demo = demo[demo['pres_year']!=2004]
vote = vote[vote['year']!=2004]
#pres_years = [2000,2004,2008,2012,2016,2020]

demo = demo.groupby(['pres_year','state','county']).mean().reset_index()

# get ready for merging with vote

demo['year'] = demo['pres_year']
demo['fips'] = 1000*demo['state']+demo['county']
demo = demo.drop(['pres_year','state','county'],axis=1)

vote['fips'] = vote['fips'].astype(int)
vote['demfr'] = vote['DEMOCRAT']/vote['totalvotes']
vote['repfr'] = vote['REPUBLICAN']/vote['totalvotes']
vote['othfr'] = vote['OTHER']/vote['totalvotes']
vote['lagdemfr'] = vote['lagDEM']/(vote['lagDEM']+vote['lagREP']+vote['lagOTH'])
vote['lagrepfr'] = vote['lagREP']/(vote['lagDEM']+vote['lagREP']+vote['lagOTH'])
vote['lagothfr'] = vote['lagOTH']/(vote['lagDEM']+vote['lagREP']+vote['lagOTH'])
vote = vote.drop(['DEMOCRAT','REPUBLICAN','OTHER','totalvotes','lagDEM','lagREP','lagOTH'],axis=1)

In [579]:
df = pd.merge(vote,demo, on=['year','fips'])

# now add polling data
### add new predictors e.g. swing - not used here

def sw(v0,vs0,d,str): 
    if(str=="ups"):
        di <- d    
    elif(str=="prop"):
        di <- d*v0/vs0
    elif(str=="pw"):
        if d>0:
            di = d*(1-v0)/(1-vs0)
        else:
            di <- d*v0/vs0
    return (di) #  Estimate of district level swing

poll = pd.DataFrame({
    'year': [2008, 2012, 2016, 2020],
    'pollDfracdiff': [0.052, -0.033, -0.020, 0.044],
    'pollRfracdiff': [-0.044, 0.036, -0.045, 0.004]
})


# seems not to work well, so will ignore for now or at least until we can get more data
#df = pd.merge(df,poll,on='year')
#df['pollupspredD'] = df['lagdemfr']+df['pollDfracdiff'] # temp fix to avoid computing overall swing
#df['pollupspredR'] = df['lagrepfr']+df['pollRfracdiff'] # temp fix to avoid computing overall swing

In [580]:
df

,Unnamed: 0,year,fips,demfr,repfr,othfr,lagdemfr,lagrepfr,lagothfr,inc,mage,fage,edu,race,malefr,femalefr
0,1,2000,1001,0.287192,0.696943,0.015865,NaN,NaN,NaN,18518.00,33.900,36.100,0.180217,0.806508,0.485929,0.514071
1,2,2000,1003,0.247822,0.723654,0.028523,NaN,NaN,NaN,20826.00,37.900,40.000,0.230663,0.871460,0.490318,0.509682
2,3,2000,1005,0.499086,0.490236,0.010678,NaN,NaN,NaN,13316.00,33.800,38.200,0.109441,0.512673,0.515531,0.484469
3,4,2000,1007,0.381636,0.601746,0.016617,NaN,NaN,NaN,14105.00,34.000,35.900,0.071049,0.766638,0.515942,0.484058
4,5,2000,1009,0.276915,0.704779,0.018305,NaN,NaN,NaN,16325.00,35.300,37.500,0.095988,0.950768,0.499294,0.500706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15567,18913,2020,56037,0.228950,0.732363,0.038687,0.188616,0.709515,0.101868,37942.75,36.550,36.725,0.202402,0.862684,0.514969,0.485031
15568,18914,2020,56039,0.665990,0.293569,0.040441,0.579235,0.310525,0.110240,69616.00,39.475,40.200,0.586076,0.845000,0.525032,0.474968
15569,18915,2020,56041,0.168200,0.792473,0.039328,0.141913,0.726564,0.131523,32137.75,36.200,36.625,0.193703,0.918191,0.507040,0.492960
15570,18916,2020,56043,0.161458,0.804812,0.033730,0.139486,0.763241,0.097273,32563.25,42.025,44.725,0.232860,0.852988,0.512510,0.487490
15571,18917,2020,56045,0.101124,0.872753,0.026124,0.084799,0.860182,0.055020,34143.75,41.850,44.400,0.178109,0.885033,0.537115,0.462885

In [585]:
# add interaction term

df = df.dropna()
df['male'] = df['malefr']*df['mage']
df['female'] = df['femalefr']*df['fage']

df_train = df[df['year']<2020]
df_test = df[df['year']==2020]
cols_to_drop1 = ['demfr','repfr','othfr','year','fips','lagothfr']
cols_to_drop2 = ['inc','mage','fage','malefr','femalefr']
cols_to_drop3 = ['edu','race','male','female']
X_train = df_train.drop(cols_to_drop1,axis=1)
X_train = X_train.drop(cols_to_drop2,axis=1)
X_train = X_train.drop(cols_to_drop3,axis=1)
X_test = df_test.drop(cols_to_drop1,axis=1)
X_test = X_test.drop(cols_to_drop2,axis=1)
X_test = X_test.drop(cols_to_drop3,axis=1)
y_train = df_train['demfr']
y_test = df_test['demfr']


#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

/var/folders/dq/tzmbpdxd3v93g7psyk_syh0m0000gn/T/ipykernel_40050/3177805206.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['male'] = df['malefr']*df['mage']
/var/folders/dq/tzmbpdxd3v93g7psyk_syh0m0000gn/T/ipykernel_40050/3177805206.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['female'] = df['femalefr']*df['fage']

In [590]:
X_train

       Unnamed: 0  lagdemfr  lagrepfr
3113         6306  0.236940  0.756735
3114         6307  0.225029  0.764152
3115         6308  0.448362  0.547369
3116         6309  0.274868  0.720000
3117         6310  0.183129  0.808501
...           ...       ...       ...
12452       15760  0.282569  0.676413
12453       15761  0.541957  0.423761
12454       15762  0.190655  0.774681
12455       15763  0.201318  0.764199
12456       15764  0.125633  0.839833

[9344 rows x 3 columns]

In [589]:
# now some basic machine learning

from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=True)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
from sklearn.metrics import mean_absolute_error,mean_squared_error

mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

MAE: 0.1370991279395502
MSE: 0.020085511259345396

In [565]:
y_err = y_pred - y_test
max(abs(y_err)), min(abs(y_err))

(0.344247824221363, 0.0008099508902663644)

In [567]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)  
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

MAE: 0.08660630674829453
MSE: 0.009516484537830638

In [365]:
y_err = y_pred - y_test
max(abs(y_err)), min(abs(y_err))

(0.32141530910030935, 2.226362107449198e-06)

In [496]:
from xgboost.sklearn import XGBRegressor
model = XGBRegressor(n_estimators=100, random_state=42) 
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

MAE: 0.06593668861846207
MSE: 0.0055010404651925915

In [354]:
y_err = y_pred - y_test
max(abs(y_err)), min(abs(y_err))

(0.34514316174851334, 1.2120306703056194e-05)

In [379]:
from lightgbm import LGBMRegressor
model = LGBMRegressor(n_estimators=100, random_state=42)  
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000498 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1530
[LightGBM] [Info] Number of data points in the train set: 9344, number of used features: 6
[LightGBM] [Info] Start training from score 0.371833
MAE: 0.030642792300509206
MSE: 0.0016405938976726498

In [380]:
y_err = y_pred - y_test
max(abs(y_err)), min(abs(y_err))

(0.3212717340143163, 1.0366114263637982e-06)

In [396]:
from sklearn import linear_model
model = linear_model.Ridge(alpha=0.7)  
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

MAE: 0.0233289216311467
MSE: 0.000983613491710235

In [397]:
y_err = y_pred - y_test
max(abs(y_err)), min(abs(y_err))

(0.17094894415774242, 5.036328229790499e-06)

In [404]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor(n_neighbors=5)  
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

MAE: 0.05572265362736988
MSE: 0.005705049022717802

In [405]:
y_err = y_pred - y_test
max(abs(y_err)), min(abs(y_err))

(0.4449282996162935, 3.1661130204974075e-05)

In [406]:
X

,year,fips,repfr,othfr,lagdemfr,lagrepfr,lagothfr,inc,mage,fage,edu,race,malefr,femalefr
0,2008,1001,0.736136,0.006133,0.201261,0.642782,0.005372,16534.333333,35.633333,37.233333,0.216862,0.785307,0.485691,0.514309
1,2012,1001,0.726183,0.007939,0.254596,0.727185,0.006059,24860.500000,36.525000,38.375000,0.219529,0.773999,0.486007,0.513993
2,2016,1001,0.727666,0.034637,0.254795,0.695912,0.007608,28295.750000,36.800000,39.175000,0.259544,0.767833,0.487547,0.512453
3,2020,1001,0.714368,0.015448,0.213756,0.654375,0.031149,33082.750000,37.775000,40.325000,0.285726,0.747263,0.485472,0.514528
4,2008,1003,0.752595,0.009286,0.191603,0.650645,0.009212,17895.333333,40.133333,42.200000,0.270185,0.856736,0.488578,0.511422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12454,2020,56043,0.804812,0.033730,0.131944,0.721974,0.092014,32563.250000,42.025000,44.725000,0.232860,0.852988,0.512510,0.487490
12455,2008,56045,0.766842,0.040422,0.169889,0.802285,0.021383,19340.333333,40.033333,44.166667,0.181441,0.955189,0.523844,0.476156
12456,2012,56045,0.839833,0.034534,0.195892,0.779399,0.041084,29108.750000,40.900000,43.575000,0.173925,0.947287,0.523331,0.476669
12457,2016,56045,0.860182,0.055020,0.119682,0.800057,0.032898,29532.750000,41.375000,45.350000,0.194480,0.940352,0.526616,0.473384
12458,2020,56045,0.872753,0.026124,0.083989,0.851966,0.054494,34143.750000,41.850000,44.400000,0.178109,0.885033,0.537115,0.462885

In [414]:
Xb = pd.merge(X_train,poll,on='year')

KeyError: 'year'

In [426]:
df

,year,fips,demfr,repfr,othfr,lagdemfr,lagrepfr,lagothfr,inc,mage,fage,edu,race,malefr,femalefr,pollDfrac,pollRfrac
0,2008,1001,0.257730,0.736136,0.006133,0.201261,0.642782,0.005372,16534.333333,35.633333,37.233333,0.216862,0.785307,0.485691,0.514309,0.521,0.445
1,2012,1001,0.265878,0.726183,0.007939,0.254596,0.727185,0.006059,24860.500000,36.525000,38.375000,0.219529,0.773999,0.486007,0.513993,0.488,0.481
2,2016,1001,0.237697,0.727666,0.034637,0.254795,0.695912,0.007608,28295.750000,36.800000,39.175000,0.259544,0.767833,0.487547,0.512453,0.468,0.436
3,2020,1001,0.270184,0.714368,0.015448,0.213756,0.654375,0.031149,33082.750000,37.775000,40.325000,0.285726,0.747263,0.485472,0.514528,0.512,0.440
4,2008,1003,0.238119,0.752595,0.009286,0.191603,0.650645,0.009212,17895.333333,40.133333,42.200000,0.270185,0.856736,0.488578,0.511422,0.521,0.445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12454,2020,56043,0.161458,0.804812,0.033730,0.131944,0.721974,0.092014,32563.250000,42.025000,44.725000,0.232860,0.852988,0.512510,0.487490,0.512,0.440
12455,2008,56045,0.192736,0.766842,0.040422,0.169889,0.802285,0.021383,19340.333333,40.033333,44.166667,0.181441,0.955189,0.523844,0.476156,0.521,0.445
12456,2012,56045,0.125633,0.839833,0.034534,0.195892,0.779399,0.041084,29108.750000,40.900000,43.575000,0.173925,0.947287,0.523331,0.476669,0.488,0.481
12457,2016,56045,0.084799,0.860182,0.055020,0.119682,0.800057,0.032898,29532.750000,41.375000,45.350000,0.194480,0.940352,0.526616,0.473384,0.468,0.436
12458,2020,56045,0.101124,0.872753,0.026124,0.083989,0.851966,0.054494,34143.750000,41.850000,44.400000,0.178109,0.885033,0.537115,0.462885,0.512,0.440

In [433]:
df.loc[:,'mage':]

,mage,fage,edu,race,malefr,femalefr,pollDfrac,pollRfrac
0,35.633333,37.233333,0.216862,0.785307,0.485691,0.514309,0.521,0.445
1,36.525000,38.375000,0.219529,0.773999,0.486007,0.513993,0.488,0.481
2,36.800000,39.175000,0.259544,0.767833,0.487547,0.512453,0.468,0.436
3,37.775000,40.325000,0.285726,0.747263,0.485472,0.514528,0.512,0.440
4,40.133333,42.200000,0.270185,0.856736,0.488578,0.511422,0.521,0.445
...,...,...,...,...,...,...,...,...
12454,42.025000,44.725000,0.232860,0.852988,0.512510,0.487490,0.512,0.440
12455,40.033333,44.166667,0.181441,0.955189,0.523844,0.476156,0.521,0.445
12456,40.900000,43.575000,0.173925,0.947287,0.523331,0.476669,0.488,0.481
12457,41.375000,45.350000,0.194480,0.940352,0.526616,0.473384,0.468,0.436
12458,41.850000,44.400000,0.178109,0.885033,0.537115,0.462885,0.512,0.440